# Generated by Django 3.1.3 on 2020-11-04 17:51

import app.core.models.save_reversion_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('url', models.URLField(max_length=250, verbose_name='URL')),
                ('actor', models.TextField(verbose_name='Actor')),
                ('resume', models.TextField(verbose_name='Resumen')),
                ('defendant', models.CharField(max_length=300, verbose_name='Demandado')),
                ('court', models.CharField(max_length=300, verbose_name='Juzgado')),
                ('state', models.CharField(max_length=200, verbose_name='Estado')),
                ('case_file', models.TextField(max_length=200, verbose_name='Expediente')),
                ('notifications', models.IntegerField(verbose_name='Notificaciones')),
            ],
            options={
                'verbose_name': 'Lista de Items',
                'verbose_name_plural': 'Listas de items',
            },
            bases=(app.core.models.save_reversion_mixin.SaveReversionMixin, models.Model),
        ),
    ]
